version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://taskuser:taskpass@db:5432/taskdb
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    command: npm run start

  frontend:
    build: ./task-manager-frontend
    depends_on:
      - backend
    ports:
      - '3000:80'
    volumes:
      - ./task-manager-frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata:
